# Issue 表单配置
# 用于 GitHub Issue Templates 的全局设置
blank_issues_enabled: false
contact_links:
  - name: "📖 快速开始（一键启动）"
    url: "https://github.com/entergirl/Ramaria/blob/main/README_快速开始（一键启动）.md"
    about: "EXE一键启动包问题先看这里！"

  - name: "📖 快速开始（从源码运行）"
    url: "https://github.com/entergirl/Ramaria/blob/main/README_快速开始（从源码运行）.md"
    about: "从源码运行相关问题先看这里！"

  - name: "📋 已有问题汇总"
    url: "https://github.com/entergirl/Ramaria/issues"
    about: "不管什么问题都先看这里！"
